disabled = false
locale = "en"
label = "English"
weight = 1
title = "@toytag.net"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "Mon, Jan 2, 2006"
  # logo = "logo.png"
  # secondaryLogo = "logo.png"
  description = "Personal website of Zhenzhong Tang, a software developer sharing projects, technical write-ups, and photography."
  copyright = "Copy, _right?_ 🤔 <br> &copy; { year } Zhenzhong Tang"

[params.author]
  name = "Zhenzhong Tang"
  image = "img/me.jpg"
  headline = "Software Engineer 🧑‍💻 @ Arista <br> CIS Alumni @ UPenn"
  bio = "Code, Debug, Rewrite, Repeat"
  links = [
    { linkedin = "https://www.linkedin.com/in/zhenzhong-tang-82334a210" },
    { instagram = "https://instagram.com/toytag12" },
    { github = "https://github.com/toytag" },
  ]
