disabled = false
locale = "zh-cn"
label = "中文"
weight = 2
title = "@toytag.net"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  # logo = "logo.png"
  # secondaryLogo = "logo.png"
  description = "汤振中的个人网站，分享软件项目、技术文章与摄影作品。"
  # copyright = "Copy, _right?_ :thinking_face: <br> &copy; { year } Zhenzhong Tang"

[params.author]
  name = "汤振中"
  image = "img/me.jpg"
  headline = "Arista Networks 程序猿 🐒 <br> UPenn CIS 校友"
  bio = "码农自学成才"
  links = [
    { linkedin = "https://www.linkedin.com/in/zhenzhong-tang-82334a210" },
    { instagram = "https://instagram.com/toytag12" },
    { github = "https://github.com/toytag" },
  ]
